# Generated by Django 5.0.6 on 2024-07-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchReq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=50, verbose_name="Должность")),
                ("exp", models.CharField(max_length=3, verbose_name="Опыт")),
                (
                    "workForm",
                    models.CharField(max_length=15, verbose_name="ФорматРаботы"),
                ),
                ("salary", models.CharField(max_length=7, verbose_name="Зарплата")),
            ],
            options={
                "verbose_name": "Поисковой запрос",
                "verbose_name_plural": "Поисковые запросы",
            },
        ),
    ]
