# Generated by Django 5.0.6 on 2024-07-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchreq",
            name="workForm",
            field=models.CharField(max_length=20, verbose_name="ФорматРаботы"),
        ),
    ]
