# Generated by Django 5.0.6 on 2024-07-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vacancies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_title",
                    models.CharField(max_length=50, verbose_name="Должность"),
                ),
                ("salary", models.CharField(max_length=6, verbose_name="Зарплата")),
                ("company", models.CharField(max_length=50, verbose_name="Компания")),
                ("city", models.CharField(max_length=20, verbose_name="Город")),
            ],
            options={
                "verbose_name": "Вакансия",
                "verbose_name_plural": "Вакансии",
            },
        ),
    ]
